# Generated by Django 3.2.6 on 2024-03-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recogination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
