# Generated by Django 3.2.6 on 2024-04-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recogination', '0002_alter_images_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='dataset/check/'),
        ),
    ]
